server {
  listen 80;
  root /usr/share/nginx/html;
  index index.html;

  # Forward requests starting with /api to the API container
  location /api/ {
    proxy_pass http://api:8000;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
  }

  # Support React Router routes and prevent 404 errors on page refresh
  location / {
    try_files $uri /index.html;
  }
}